spring:
  elasticsearch:
    jest:
      uris: http://192.168.0.101:9200
      connection-timeout: 30s
      read-timeout: 30s
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.0.101:9300